# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lobby import Lobby  # noqa: E501
from swagger_client.rest import ApiException


class TestLobby(unittest.TestCase):
    """Lobby unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLobby(self):
        """Test Lobby"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lobby.Lobby()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
