# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.network_api import NetworkApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_network_ip_v4_get(self):
        """Test case for network_ip_v4_get

        Sends a plaintext representation of the callers ipv4 address  # noqa: E501
        """
        pass

    def test_network_ip_v6_get(self):
        """Test case for network_ip_v6_get

        Sends a plaintext representation of the callers ipv6 address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
