# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.players_api import PlayersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlayersApi(unittest.TestCase):
    """PlayersApi unit test stubs"""

    def setUp(self):
        self.api = PlayersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_players_names_name_get(self):
        """Test case for players_names_name_get

        Checks if a player name is available  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
