# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lobbies_api import LobbiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLobbiesApi(unittest.TestCase):
    """LobbiesApi unit test stubs"""

    def setUp(self):
        self.api = LobbiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_lobby(self):
        """Test case for create_lobby

        creates a new lobby  # noqa: E501
        """
        pass

    def test_join_lobby(self):
        """Test case for join_lobby

        Join an existing lobby  # noqa: E501
        """
        pass

    def test_lobbies_lobby_name_events_event_post(self):
        """Test case for lobbies_lobby_name_events_event_post

        Post an event to a lobby such as GameStarted or GameEnded  # noqa: E501
        """
        pass

    def test_lobbies_lobby_name_players_player_name_event_post(self):
        """Test case for lobbies_lobby_name_players_player_name_event_post

        Post a player event to a lobby such as connected, disconnected, kicked  # noqa: E501
        """
        pass

    def test_pulse_lobby(self):
        """Test case for pulse_lobby

        Heartbeat for a lobby  # noqa: E501
        """
        pass

    def test_search_lobbies(self):
        """Test case for search_lobbies

        Pulls a list of available lobbies  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
