# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LobbyMember(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'player_name': 'str',
        'ip': 'str',
        'is_ip_v4': 'bool',
        'player_profile': 'Player'
    }

    attribute_map = {
        'player_name': 'playerName',
        'ip': 'ip',
        'is_ip_v4': 'isIpV4',
        'player_profile': 'playerProfile'
    }

    def __init__(self, player_name=None, ip=None, is_ip_v4=None, player_profile=None):  # noqa: E501
        """LobbyMember - a model defined in Swagger"""  # noqa: E501
        self._player_name = None
        self._ip = None
        self._is_ip_v4 = None
        self._player_profile = None
        self.discriminator = None
        self.player_name = player_name
        self.ip = ip
        if is_ip_v4 is not None:
            self.is_ip_v4 = is_ip_v4
        if player_profile is not None:
            self.player_profile = player_profile

    @property
    def player_name(self):
        """Gets the player_name of this LobbyMember.  # noqa: E501


        :return: The player_name of this LobbyMember.  # noqa: E501
        :rtype: str
        """
        return self._player_name

    @player_name.setter
    def player_name(self, player_name):
        """Sets the player_name of this LobbyMember.


        :param player_name: The player_name of this LobbyMember.  # noqa: E501
        :type: str
        """
        if player_name is None:
            raise ValueError("Invalid value for `player_name`, must not be `None`")  # noqa: E501

        self._player_name = player_name

    @property
    def ip(self):
        """Gets the ip of this LobbyMember.  # noqa: E501


        :return: The ip of this LobbyMember.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this LobbyMember.


        :param ip: The ip of this LobbyMember.  # noqa: E501
        :type: str
        """
        if ip is None:
            raise ValueError("Invalid value for `ip`, must not be `None`")  # noqa: E501

        self._ip = ip

    @property
    def is_ip_v4(self):
        """Gets the is_ip_v4 of this LobbyMember.  # noqa: E501


        :return: The is_ip_v4 of this LobbyMember.  # noqa: E501
        :rtype: bool
        """
        return self._is_ip_v4

    @is_ip_v4.setter
    def is_ip_v4(self, is_ip_v4):
        """Sets the is_ip_v4 of this LobbyMember.


        :param is_ip_v4: The is_ip_v4 of this LobbyMember.  # noqa: E501
        :type: bool
        """

        self._is_ip_v4 = is_ip_v4

    @property
    def player_profile(self):
        """Gets the player_profile of this LobbyMember.  # noqa: E501


        :return: The player_profile of this LobbyMember.  # noqa: E501
        :rtype: Player
        """
        return self._player_profile

    @player_profile.setter
    def player_profile(self, player_profile):
        """Sets the player_profile of this LobbyMember.


        :param player_profile: The player_profile of this LobbyMember.  # noqa: E501
        :type: Player
        """

        self._player_profile = player_profile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LobbyMember, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LobbyMember):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
