# coding: utf-8

"""
    Simple Matchmaking API

    This is a simple matchmaking API API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Player(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'password': 'str',
        'games_won': 'int',
        'games_lost': 'int'
    }

    attribute_map = {
        'name': 'name',
        'password': 'password',
        'games_won': 'gamesWon',
        'games_lost': 'gamesLost'
    }

    def __init__(self, name=None, password=None, games_won=None, games_lost=None):  # noqa: E501
        """Player - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._password = None
        self._games_won = None
        self._games_lost = None
        self.discriminator = None
        self.name = name
        self.password = password
        if games_won is not None:
            self.games_won = games_won
        if games_lost is not None:
            self.games_lost = games_lost

    @property
    def name(self):
        """Gets the name of this Player.  # noqa: E501


        :return: The name of this Player.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Player.


        :param name: The name of this Player.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def password(self):
        """Gets the password of this Player.  # noqa: E501


        :return: The password of this Player.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Player.


        :param password: The password of this Player.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def games_won(self):
        """Gets the games_won of this Player.  # noqa: E501


        :return: The games_won of this Player.  # noqa: E501
        :rtype: int
        """
        return self._games_won

    @games_won.setter
    def games_won(self, games_won):
        """Sets the games_won of this Player.


        :param games_won: The games_won of this Player.  # noqa: E501
        :type: int
        """

        self._games_won = games_won

    @property
    def games_lost(self):
        """Gets the games_lost of this Player.  # noqa: E501


        :return: The games_lost of this Player.  # noqa: E501
        :rtype: int
        """
        return self._games_lost

    @games_lost.setter
    def games_lost(self, games_lost):
        """Sets the games_lost of this Player.


        :param games_lost: The games_lost of this Player.  # noqa: E501
        :type: int
        """

        self._games_lost = games_lost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Player, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Player):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
